### ISSUE TITLE
module version incompatibility

### ISSUE THREAD

**Issue by M4rkoffka** [codesandbox/codesandboxer#44]
hello, can i update node on codesandbox nuxt project?
when i install module **prismic-nuxt** it except node v **9.0.0**  but i have **8.14**
`error prismic-nuxt@0.3.0: The engine "node" is incompatible with this module. Expected version ">= 9.0.0". Got "8.14.0"`

**Comment by Noviny** [comment]
Hey,

This project doesn't specify a node engine. I'd guess this error is coming from somewhere else?
