### ISSUE TITLE
Multiple Files / Nested Directories? Out of Scope?

### ISSUE THREAD

**Issue by karlhorky** [codesandbox/codesandboxer#62]
Hi there! Thanks for this project, looks really useful!

I wanted to ask if it would be out of scope to allow creation of a sandbox using multiple files instead of a single file.

And if that is not out of scope, to take it one step further - to allow recursive directories with files within them?

Oh, and I'm assuming that this can be used with local files too (private repo) - while reading the docs quickly it seemed like this may be possible.

My use case is that I have example folders with multiple HTML, CSS, JavaScript and TypeScript files in them, and I would like to generate a Sandbox URL with these files (should be updated when the files are updated).

Up until now I've been using the excellent [elboman/gatsby-remark-embedded-codesandbox](https://github.com/elboman/gatsby-remark-embedded-codesandbox), but I would like to move away from Gatsby and so I'm looking at other alternatives.

**Comment by Noviny** [comment]
Hey! I think this is probably out-of-scope for this library, but want to understand your use-case well enough.

There's a separate (probably should be merged) codesandbox extension designed at deploying a github repo, which sounds more like what you want, though I am guessing you want to specify a subset of files within a repo?

I think using codesandbox's API it would not actually be too hard to write a function where you pass in an array of files, and it uploads all those selected files as a single sandbox, creating the multiple entrypoints feature you want / subset of repository.

Biggest reason to not try and add this here is that we are laser focused on rendering a component, and resolving imports needed for that component. Uploading a folder is different enough I don't know how much of the logic it would share.

I'm closing this for now, but if you want to talk further about it, feel free to come back to me to discuss further, or reopen this if you don't feel this was addressed.

**Comment by karlhorky** [comment]
> I think this is probably out-of-scope for this library
> we are laser focused on rendering a component

Understood! That makes sense.

> I think using codesandbox's API it would not actually be too hard to write a function where you pass in an array of files, and it uploads all those selected files as a single sandbox, creating the multiple entrypoints feature you want / subset of repository.

Yep, I think I could probably learn a lot from https://github.com/elboman/gatsby-remark-embedded-codesandbox/blob/master/src/index.js and https://github.com/elboman/gatsby-remark-embedded-codesandbox/pull/6. May need to dive in and do it myself at some point.

> want to understand your use-case well enough
> I am guessing you want to specify a subset of files within a repo?

Yes, so like I mentioned above in my comment:

> My use case is that I have example folders with multiple HTML, CSS, JavaScript and TypeScript files in them, and I would like to generate a Sandbox URL with these files (should be updated when the files are updated).

...I would like to be able to create web development programming exercises for our students at @upleveled, so that they can solve problems in an online environment before having set up their computer.
