### ISSUE TITLE
Preview pane is broken when creating sandboxes on Chrome

### ISSUE THREAD

**Issue by declan-warn** [codesandbox/codesandboxer#72]
## Description
When creating sandboxes on Chrome through `codesandboxer` (at least with `react-codesandboxer`) the preview pane is blank in the created sandbox. This does not affect other browsers, and can be worked around by copying the sandbox URL into another tab.

This is affecting many different websites:
* [Atlaskit](https://atlaskit.atlassian.com/packages/design-system/blanket/example/basic-usage)
* [Garden](https://garden.zendesk.com/components/button)
* [Gestalt](https://gestalt.netlify.app/Button)
* [PatternFly](https://www.patternfly.org/v4/components/button/)
* [Polaris](https://polaris.shopify.com/components/actions/button)

Sandboxes created through other means do not seem to be affected. This includes through the CodeSandbox website as well as directly through the API.
[Carbon](https://www.carbondesignsystem.com/components/button/code/) is unaffected, most likely because [they use the API directly](https://github.com/carbon-design-system/carbon-website/blob/bc1c419affa848852d304c157aa13247b0a0c409/src/components/ComponentDemo/Code/useCodesandbox.js).

## To reproduce
Go to any of the affected sites linked above and use the open sandbox button in Chrome. The preview panel will not show anything, and will just be blank.

## Environment
**OS:** macOS Catalina 10.15.7
**Browser:** Chrome 88.0.4324.182

**Comment by declan-warn** [comment]
I think this is actually affecting other browsers as well.

**Comment by seancurtis** [comment]
I did some testing:

**Broken**

- Google Chrome — 88.0.4324.182
- Google Chrome Canary — 90.0.4421.0
- Firefox — 85.0.1

**Working**

- Firefox — 84.0.1
- Safari — 14.0.3
- Edge — 88.0.705.68

It was working when I initially tried Firefox, but once updating to 85 it no longer worked.
